INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (1, 'Playstation 5');
INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (10, 'Xbox One');
INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (20, ' Xbox Series S');
INSERT INTO TBL_PRODUCT (PRICE, PRODUCT_NAME) VALUES (30, ' Xbox Series X');
